# Generated by Django 4.2.18 on 2025-08-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('google_email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('client', 'Client'), ('stylist', 'Stylist'), ('admin', 'Admin')], default='client', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
