# Generated by Django 4.2.18 on 2025-08-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tressreliefapi', '0002_category_service_stylistservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
