# Generated by Django 4.2.18 on 2025-09-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tressreliefapi', '0003_userinfo_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='owner_uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
