# Generated by Django 4.2.18 on 2025-09-12 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tressreliefapi', '0004_service_owner_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='google', max_length=32)),
                ('refresh_token', models.TextField()),
                ('access_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tressreliefapi.userinfo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='oauthcredential',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_provider'),
        ),
    ]
